# Generated by Django 5.2.7 on 2025-11-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habr', '0003_articledeleterequest_articleeditrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Alternative: use Cloudinary URL if not uploading file'),
        ),
    ]
